val scalaJSVersion = Option(System.getenv("SCALAJS_VERSION")).getOrElse("1.18.2")

addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"             % "0.11.1")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.4.6")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"            % "2.0.10")
addSbtPlugin("org.jmotor.sbt"     % "sbt-dependency-updates"   % "1.2.9")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.1")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % scalaJSVersion)
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"             % "3.11.2")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"                  % "2.0.1")
addSbtPlugin("com.github.gseitz"  % "sbt-release"              % "1.0.13")
